#include QMK_KEYBOARD_H

bool MAC_mode = false;

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
[_NUM] = LAYOUT_ortho_5x5( \
	KC_ESC, KC_F2, LCTL(KC_1), KC_DEL, KC_BSPC, \
	KC_7, KC_8, KC_9, KC_COLN, LT(_FN, KC_HOME), \
	KC_4, KC_5, KC_6, KC_SLSH, LT(_RGB, KC_END), \
	KC_1, KC_2, KC_3, KC_UP, KC_PENT, \
	KC_0, SFT_T(KC_DOT), KC_LEFT, KC_DOWN, KC_RGHT),\

[_FN] = LAYOUT_ortho_5x5( \
	KC_F10, KC_F11, KC_F12, KC_TRNS, KC_NLCK, \
	KC_F7, KC_F8, KC_F9, KC_TRNS, XXXXXXX, \
	KC_F4, KC_F5, KC_F6, KC_TRNS, KC_TRNS, \
	KC_F1, KC_F2, KC_F3, KC_TRNS, KC_TRNS, \
	XXXXXXX, XXXXXXX, KC_TRNS, KC_TRNS, KC_TRNS), \

[_RGB] = LAYOUT_ortho_5x5( \
	RGB_TOG, RGB_MODF, RGBHINC, RGBSINC, RGBVINC, \
  RGBRST,  RGB_MODR, RGBHDEC, RGBSDEC, RGBVDEC, \
	RGB_MODE_PLAIN, RGB_MODE_BREATHE, RGB_MODE_RAINBOW, XXXXXXX, XXXXXXX, \
	RGB_MODE_SWIRL, RGB_MODE_SNAKE, RGB_MODE_KNIGHT, XXXXXXX, XXXXXXX, \
	KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS) \
};
