#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(KC_RGHT, KC_DOWN, KC_LEFT, KC_ESC, KC_LCTL, KC_LSFT, KC_BSPC, KC_UP, KC_HENK, KC_MHEN, KC_LALT, KC_APP)
};
